### ISSUE TITLE
Cannot preview xlsx format dataset 

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#77]
@olafveerman Upload 3 excel workbook xlsx format files <https://energydata.info/dataset/making-power-affordable-for-africa-and-viable-for-its-utilities>, but cannot be previewed as below: 
<img width="956" alt="screenshot 2017-01-10 22 38 52" src="https://cloud.githubusercontent.com/assets/6911487/21835044/e680d828-d787-11e6-9347-2afa268377a0.png">

**Comment by olafveerman** [comment]
@kamicut Datapusher doesn't seem to be running. 

`$ datacats logs --datapusher`

```
Traceback (most recent call last):
  File "datapusher/main.py", line 5, in <module>
    import jobs
  File "/project/datapusher/datapusher/jobs.py", line 19, in <module>
    import messytables
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/messytables/__init__.py", line 21, in <module>
    from messytables.html import HTMLTableSet, HTMLRowSet
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/messytables/html.py", line 4, in <module>
    import html5lib
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/html5lib/__init__.py", line 16, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/html5lib/html5parser.py", line 2, in <module>
    from six import with_metaclass, viewkeys, PY3
ImportError: cannot import name viewkeys
```

**Comment by olafveerman** [comment]
@Naigege 
We fixed the underlying Datapusher issue.

If there are tabular datasets that are not behaving as expected, please go to 'Manage' -> 'Datastore'.
If you see an error like the one in the screenshot, hit the 'Upload to Datastore' button:

![image](https://cloud.githubusercontent.com/assets/751330/23866954/c0fd14ba-07f0-11e7-8c3e-28783c65b707.png)

**Comment by Naigege** [comment]
@olafveerman Thanks! I am checking the csv & xlsx files, still see some xlsx preview issues:

1. Africa - The electricity supply system (2016) <https://energydata.info/dataset/africa-the-electicity-supply-system/resource/7c8207ba-8d4d-4c22-88d0-81a8add21a85>. There is a datastore error:
![image](https://cloud.githubusercontent.com/assets/6911487/23872693/a32bf41e-0805-11e7-9654-cf58fcf9cda9.png)

2. The preview is not working and no Data API button <https://energydata.info/dataset/zambia-wind-measurement-data/resource/5ba046c5-be8b-4f0a-bf93-6ece5eeae754>, but uploading to datastore is completed:
![image](https://cloud.githubusercontent.com/assets/6911487/23872772/f217ef74-0805-11e7-9ded-492d0de379ab.png)

**Comment by olafveerman** [comment]
@Naigege 
Datapusher is built to parse tabular data and does a decent job of detecting headers, guessing field types, and so on. In all of these cases, Datapusher has trouble parsing the file.

1. This file consists of a lot of different sheets, double headers, empty columns, etc
2. This file contains a lot of metadata, merged cells, etc The actual data starts only on row 25
![image](https://cloud.githubusercontent.com/assets/751330/23901023/de3e18de-0891-11e7-95e4-5f3c851bb260.png)
3. This file also seems to contain a lot of meta-data, with the actual data starting on row 25

**Comment by Naigege** [comment]
@olafveerman Thanks! Is there any other way for us to visualize those kind of excel files? 

If not, can we modify the preview error message and let users to download the dataset directly? B/c we cannot control what kind of excel files will be uploaded. Right now, it shows error message like this:
<img width="969" alt="screenshot 2017-03-14 14 53 18" src="https://cloud.githubusercontent.com/assets/6911487/23917856/29b3fccc-08c7-11e7-93c7-75b132f691a4.png">
